String.toLocaleString({
"en": {
    "%title": "SPViewer(en)",
    "%info": "Radioisotope spectrum viewer",
    "%menu1": "Select",
    "%menu2": "View",
    "%menu3": "Setting",
    "%spectrumList": "Select Spectrum",
    "%spectrumView": "View Spectrum",
    "%spectrumEdit": "Spectrum Setting",
    "%sp_info": "Spectrum Information",
    "%zoom": "Zoom in",
    "%zoomout": "Zoom out",
    "%bg_range": "BG width",
    "%bg_range_left": "Left side BG",
    "%bg_range_right": "Right side BG",
    "%v_range": "max Y",
    "%f_type": "Filter",
    "%none": "None",
    "%sma": "Simple average",
    "%wma": "Simple average",
    "%log": "log",
    "%sp_cursor_info": "* Cursor info",
    "%sp_cursor_info_compare": "* Cursor info",
    "%sp_cursor_info_multi": "* Cursor info",
    "%sp_cursor_nuclear": "* Isotope info",
    "%energy": "energy",
    "%isotope": "isotope",
    "%halflife": "halflife",
    "%percentage": "percentage",
    "%sp_cursor_selection": "* selected region",
    "%startch": "Start ch",
    "%endch": "End ch",
    "%startev": "Start ev",
    "%endev": "End ev",
    "%grosscps": "Gross cps(with BG)",
    "%netcps": "Net cps(w/o BG)",
    "%grosscount": "Gross count(with BG)",
    "%netcount": "Net count(w/o BG)",
    "%sp_cursor_selection_compare": "* Selected region",
    "%endev2": "End ev",
    "%sp_cursor_selection_multi": "* Selected region",
    "%startev3": "Start ev",
    "%endev3": "End ev"
},
"ja": {
    "%title": "SPViewer(ja)",
    "%info": "放射線スペクトル表示ツール",
    "%menu1": "スペクトル選択",
    "%menu2": "スペクトル表示",
    "%menu3": "描画要素変更",
    "%spectrumList": "スペクトル選択",
    "%spectrumView": "スペクトル表示",
    "%spectrumEdit": "セッティング変更",
    "%sp_info": "■ スペクトル情報",
    "%zoom": "選択範囲を拡大",
    "%zoomout": "ズームアウト",
    "%bg_range": "BG計算幅",
    "%bg_range_left": "左側BG範囲を選ぶ",
    "%bg_range_right": "右側BG範囲を選ぶ",
    "%v_range": "縦軸表示範囲",
    "%f_type": "フィルタ",
    "%none": "なし",
    "%sma": "単純移動平均",
    "%wma": "加重移動平均",
    "%log": "対数表示",
    "%sp_cursor_info": "■ カーソル位置情報",
    "%sp_cursor_info_compare": "■ カーソル位置情報",
    "%sp_cursor_info_multi": "■ カーソル位置情報",
    "%sp_cursor_nuclear": "■ カーソル位置核種情報",
    "%energy": "エネルギー",
    "%isotope": "核種",
    "%halflife": "半減期",
    "%percentage": "放出比",
    "%sp_cursor_selection": "■ 選択範囲情報",
    "%startch": "始ch",
    "%endch": "終ch",
    "%startev": "始ev",
    "%endev": "終ev",
    "%grosscps": "グロスcps(BG含)",
    "%netcps": "ネットcps(BG除)",
    "%grosscount": "グロスcount(BG含)",
    "%netcount": "ネットcount(BG除)",
    "%sp_cursor_selection_compare": "■ 選択範囲情報",
    "%startev2": "始ev",
    "%endev2": "終ev",
    "%sp_cursor_selection_multi": "■ 選択範囲情報",
    "%startev3": "始ev",
    "%endev3": "終ev"
}
});
